name: SonarCloud Analysis

on:
  push:
    branches:
      - '**' # This ensures it runs on EVERY branch

jobs:
  sonarcloud:
    name: Run Code Scanning
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for SonarCloud to analyze all history properly

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Run Tests and Sonar Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew test jacocoTestReport sonar --info